Update runsql, start working on initial schema

diff --git a/tools/runsql b/tools/runsql
--- a/tools/runsql
+++ b/tools/runsql
@@ -2,12 +2,10 @@
 set -o pipefail
 
 top=`git rev-parse --show-cdup || echo "Assuming $PWD is top." >&2`
-conf=${top}conf
-db=default
-evolutions=$conf/evolutions/$db
+schema=${top}schema
 
-if [[ ! -f $conf/application.conf ]] ; then
-	echo "$conf/application.conf is missing.  You are probably in the wrong directory."
+if [[ ! -f ${schema}.sql ]] ; then
+	echo "${schema}.sql is missing.  You are probably in the wrong directory."
 	exit 1
 fi
 
@@ -19,122 +17,96 @@ if [[ ! -f ${top}local.conf ]] ; then
 	exit 1
 fi
 
-getconfig () {
-	# This isn't perfect but hopefully good enough
-	sed -n '/^'"$1"'=\("\([^"]*\)"\|\([^# ]*\)\).*$/{s//\2\3/;p;q}' ${top}local.conf $conf/application.conf
-}
-
 getdbconfig () {
-	getconfig "db\.$db\.$1"
+	# This isn't perfect but hopefully good enough
+	sed -n '/^db\s*{/,/^}/{/^\s*\([a-z]\+\)\s*=\s*/{s//\1 /;s/^\([a-z]\+ \)"\(.*\)"$/\1\2/;s/\$(USER)/'"$USER"'/;p}}' ${top}databrary.conf ${top}local.conf
 }
 
-getdb () {
-	sed -n '/^jdbc:postgresql:\(\/\/\([^\/:]\+\)\(:\([0-9]\+\)\)\?\/\)\?\([^?]*\).*$/{s//host="\2";port="\4";database="\5"/;p}'
-}
+declare -A db=([port]=5432)
+while read key val ; do
+	db[$key]=$val
+done < <(getdbconfig)
 
-eval $(getdbconfig url | getdb)
-user=`getdbconfig user`
-password=`getdbconfig password`
-: ${host:=localhost} ${port:=5432} ${database:=$user}
+if [[ -z ${db[db]} || -z ${db[user]} ]] ; then
+	echo "Could not read database configuration."
+	exit 1
+fi
 
-if [[ ! -f ~/.pgpass ]] ; then
+if [[ -n ${db[pass]} && ! -f ~/.pgpass ]] ; then
 	um=`umask -p`
 	umask 077
-	echo "$host:$port:$database:$user:$password" >> ~/.pgpass
+	echo "${db[host]:-localhost}:${db[port]}:${db[db]}:${db[user]}:${db[pass]}" >> ~/.pgpass
 	$um
 fi
 
-args=(-h $host -p $port -U $user)
+declare -a args
+if [[ -n ${db[host]} ]] ; then
+	args=(-h ${db[host]} -p ${db[port]})
+elif [[ -n ${db[sock]} ]] ; then
+	args=(-h ${db[sock]%/.s.PGSQL.*})
+fi
+args=("${args[@]}" -U ${db[user]})
 while [[ $1 = -?* ]] ; do
 	args=("${args[@]}" $1)
 	shift
 done
 
 runsql () {
-	psql -q "${args[@]}" -vON_ERROR_STOP=on -f "${@:--}" "${database}"
+	psql -q "${args[@]}" -vON_ERROR_STOP=on -f "${@:--}" "${db[db]}"
 }
 
 dbreset () {
 	if [[ -z $1 ]] ; then
-		pg_dump -Fc -f unreset.dump "${args[@]}" "${database}"
+		pg_dump -Fc -f unreset.dump "${args[@]}" "${db[db]}"
 	fi
-	runsql $conf/reset.sql
+	runsql <<EOF
+DROP SCHEMA IF EXISTS public, audit, ingest CASCADE;
+CREATE SCHEMA public;
+EOF
 }
-
-# play does _.trim on each line, which has weird semantics:
-trim='s/^[\c@- ]*//;s/[\c@- ]*$//'
 
 schema () {
-	sed "$trim" $conf/schema.sql | runsql
-}
-
-declare -A evomark=([up]='/^#.*!Ups/' [down]='/^#.*!Downs/')
-declare -A evoexpr=([up]="0,${evomark[up]}d;${evomark[down]}q" [down]="1,${evomark[down]}d")
-evolution () {
-	sed -n "$trim;${evoexpr[$1]};/[^\\c@- ]/,\$p" $evolutions/$2.sql
-}
-
-evolution_hash () {
-	echo -n "$(evolution down $1)$(evolution up $1)" | sha1sum | cut -d' ' -f1
-}
-
-evolve () {
-	local dir=$1 ; shift
-	for id in "$@" ; do
-		if [[ -n $play ]] ; then
+	if [[ -z $1 ]] ; then
+		runsql $schema.sql
+	else
+		if [[ $1 = 0 ]] ; then
 			runsql <<EOF
-DELETE FROM play_evolutions WHERE id = $id;
+CREATE TABLE schema (name varchar(64) Primary Key, applied timestamptz NOT NULL Default now());
+EOF
+		else
+			runsql <<EOF
+INSERT INTO schema (name) VALUES ('$1');
 EOF
 		fi
-		if [[ -z $fake ]] ; then
-			evolution $dir $id | sed 's/;;/;/g' | runsql
-		fi
-		if [[ -n $play && $dir = up ]] ; then
-			runsql <<EOF
-INSERT INTO play_evolutions VALUES ($id, '`evolution_hash $id`', CURRENT_TIMESTAMP, \$evolution_up\$$(evolution up $id)\$evolution_up\$, \$evolution_down\$$(evolution down $id)\$evolution_down\$, 'applied');
-EOF
-		fi
-	done
+		runsql $schema/$1.sql
+	fi
 }
 
 check_dump() {
-	pg_dump -O -f $conf/check-$1.sql "${args[@]}" "${database}"
+	mkdir -p $schema/check
+	pg_dump -O -f $schema/check/$1.sql "${args[@]}" "${db[db]}"
 }
 
 check_diff() {
 	check_dump $2
 	echo "Checking $1 vs. $2..."
-	diff -F'^[A-Z]' -u0 $conf/check-$1.sql $conf/check-$2.sql || (
+	diff -F'^[A-Z]' -u0 $schema/check/$1.sql $schema/check/$2.sql || (
 		echo -n "OK? "
 		read y
 		[[ -z $y || $y = y* ]]
 	)
 }
 
-evolve_all () {
-	n=0
-	if [[ -n $play ]] ; then
-		runsql <<EOF
-CREATE TABLE play_evolutions (id integer primary key, hash varchar(255) not null, applied_at timestamp not null, apply_script text, revert_script text, state varchar(255), last_problem text);
-EOF
-	fi
-	while [[ -f $evolutions/$[++n].sql ]] ; do
+schema_all () {
+	for s in $schema/*.sql ; do
+		s=${s%.sql}
+		s=${s#$schema/}
 		if [[ -n $1 ]] ; then
-			check_dump up-$n
+			check_dump $s
 		fi
-		echo "Running evolution up $n..."
-		evolve up $n
+		echo "Running schema $s..."
+		schema $s
 	done
-}
-
-opts () {
-	local opts=$1 ; shift
-	OPTIND=1
-	while getopts "$opts" opt ; do case "$opt" in
-		p) play=1 ;;
-		P) play=1 ; fake=1 ;;
-		?) exit 1 ;;
-	esac ; done
 }
 
 usage () {
@@ -143,8 +115,7 @@ Usage:
   runsql  		run psql interactively
   runsql -|<file>	execute contents of file
   runsql reset		reset the database (clear public schema)
-  runsql schema	[-p]	apply master schema
-  runsql up|down [-pP] [NUM]	run evolution NUM
+  runsql schema	[NAME]	apply [master] schema
   runsql check		apply and compare master schema and evolutions
   runsql dump ARGS.. 	run pg_dump
   runsql restore ARGS.. run pg_restore
@@ -154,7 +125,7 @@ EOF
 
 if [[ $# -eq 0 ]] ; then
 	echo "Use '$0 help' for help"
-	exec psql "${args[@]}" "${database}"
+	exec psql "${args[@]}" "${db[db]}"
 elif [[ $1 = help && $# -eq 1 ]] ; then
 	usage
 elif [[ $# -eq 1 && ( $1 = - || -f $1 ) ]] ; then
@@ -163,61 +134,35 @@ elif [[ $1 = reset && $# -eq 1 ]] ; then
 	dbreset
 elif [[ $1 = schema ]] ; then
 	shift
-	opts 'p' "$@"
-	if [[ $# -ge $OPTIND ]] ; then
-		usage
-		exit 1
-	fi
-	dbreset
-	schema
-	if [[ -n $play ]] ; then
-		fake=1
-		evolve_all
-	fi
-elif [[ $# -eq 2 && $1 = hash ]] ; then
-	shift
-	evolution_hash "$@"
-elif [[ $1 = up || $1 = down ]] ; then
-	cmd=$1 ; shift
-	opts 'pP' "$@"
-	shift $[OPTIND-1]
 	if [[ $# -eq 0 ]] ; then
-		if [[ -z $fake ]] ; then
-			dbreset
-		fi
-		evolve_all
-	elif [[ $# -eq 1 ]] ; then
-		evolve $cmd "$@"
+		dbreset
+		schema
 	else
-		usage
-		exit 1
+		for l in "$@" ; do
+			schema $l
+		done
 	fi
 elif [[ $1 = check ]] ; then
 	dbreset
-	if ! [[ $conf/check-schema.sql -nt $conf/schema.sql ]] ; then
+	if ! [[ $schema/check/schema.sql -nt $schema.sql ]] ; then
 		echo "Running schema..."
 		schema
 		check_dump schema
 	fi
 	dbreset 1
-	evolve_all 1
+	schema_all 1
 	check_diff schema evolve
-	while [[ $[--n] -ge 1 ]] ; do
-		echo "Running evolution down $n..."
-		evolve down $n
-		check_diff up-$n down-$n
-	done
-	rm -f $conf/check-*.sql
+	rm -rf $schema/check
 elif [[ $1 = dump ]] ; then
 	shift
-	exec pg_dump "${args[@]}" "$@" "${database}"
+	exec pg_dump "${args[@]}" "$@" "${db[db]}"
 elif [[ $1 = restore ]] ; then
 	shift
 	if [[ $# -eq 0 ]] ; then
 		set -- unreset.dump
 	fi
 	dbreset 1
-	exec pg_restore "${args[@]}" -d "${database}" -O "$@"
+	exec pg_restore "${args[@]}" -d "${db[db]}" -O "$@"
 else
 	usage
 	exit 1
